/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */


#ifdef __cplusplus
}
#endif

JNIEXPORT  jobject JNICALL Java_android_1serialport_1api_SerialPort_open
(JNIEnv*, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
#ifdef __cplusplus
}
#endif

JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_close
(JNIEnv *, jobject);
#endif

#ifdef __cplusplus
}
#endif
